// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  logUserIdentity: __t.identity().name("log_user_identity"),
  actionType: __t.string().name("action_type"),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  detailsJson: __t.string().name("details_json"),
  createdAt: __t.timestamp().name("created_at"),
});
