// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  matchUserIdentity: __t.identity().name("match_user_identity"),
  petExternalId: __t.string().name("pet_external_id"),
  score: __t.u8(),
  reasonsJson: __t.string().name("reasons_json"),
  warningsJson: __t.string().name("warnings_json"),
  filteredOut: __t.u8().name("filtered_out"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
