// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  draftUserIdentity: __t.identity().name("draft_user_identity"),
  petExternalId: __t.string().name("pet_external_id"),
  organizationExternalId: __t.string().name("organization_external_id"),
  message: __t.string(),
  status: __t.string(),
  approvedAt: __t.string().name("approved_at"),
  sentAt: __t.string().name("sent_at"),
  simulated: __t.u8(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
