// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  externalId: __t.string().name("external_id"),
  organizationExternalId: __t.string().name("organization_external_id"),
  name: __t.string(),
  species: __t.string(),
  breed: __t.string(),
  age: __t.string(),
  petSize: __t.string().name("pet_size"),
  energyLevel: __t.string().name("energy_level"),
  groomingNeeds: __t.string().name("grooming_needs"),
  goodWithKids: __t.u8().name("good_with_kids"),
  goodWithDogs: __t.u8().name("good_with_dogs"),
  goodWithCats: __t.u8().name("good_with_cats"),
  allergyNotes: __t.string().name("allergy_notes"),
  monthlyCostCents: __t.u32().name("monthly_cost_cents"),
  distanceMiles: __t.u32().name("distance_miles"),
  description: __t.string(),
  imageUrl: __t.string().name("image_url"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
