// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  questionnaireUserIdentity: __t.identity().name("questionnaire_user_identity"),
  firebaseUid: __t.string().name("firebase_uid"),
  responseJson: __t.string().name("response_json"),
  zipCode: __t.string().name("zip_code"),
  preferredSpecies: __t.string().name("preferred_species"),
  budgetCents: __t.u32().name("budget_cents"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
