// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  externalId: __t.string(),
  organizationExternalId: __t.string(),
  name: __t.string(),
  species: __t.string(),
  breed: __t.string(),
  age: __t.string(),
  petSize: __t.string(),
  energyLevel: __t.string(),
  groomingNeeds: __t.string(),
  goodWithKids: __t.u8(),
  goodWithDogs: __t.u8(),
  goodWithCats: __t.u8(),
  allergyNotes: __t.string(),
  monthlyCostCents: __t.u32(),
  distanceMiles: __t.u32(),
  description: __t.string(),
  imageUrl: __t.string(),
};
